### ISSUE TITLE
!be is slow the first time it is run

### ISSUE THREAD

**Issue by fimad** [numberten/zhenya_bot#9]
N-gram distributions are computed lazily which makes zbot start faster, but it means it takes a couple seconds to impersonate someone for the first call :(

Proposed solution: either strictly compute the distributions on load, or in a background thread to compute.

**Comment by numberten** [comment]
I like the idea of computing it as a background thread. I think that's something we could generalize though. 

Should we consider giving components some means of running load/unload functions? Unload functions would need to to contain non-critical code, due to the number of unsafe shutdowns.

**Comment by fimad** [comment]
We already have onload like functionality. Since registering a component requires a Bot BotComponent, and Bot wraps IO, we can wrap any onload operation we want in the Bot monad and prepend it to the component with >>.

I'm still not sold on unload. Dirty shut downs are so common that any component that cares will have to have logic they deals with that possibility.

Do we have a use case for unload?

**Comment by numberten** [comment]
Loads:
Do you have an example of this? When I tried this my prepended action didn't run on load. 

Unloads:
Unload is definitely the harder one to place, functionality wise. The only future use case that comes to mind is a component that keeps some sort of state and regularly writes its state to disk (on a timer or such). If we moved all writes to unload, then we'd lose a lot every time there's an unexpected shutdown, but I could see it being useful in a hypothetical case where state is saved on a timer as well as unloads. 

In a case like that we'd lose data gathered between the last save and the unsafe shutdown, in the worst case, and nothing in the manual shutdown case.

I don't think this is something we should worry about for now, since I haven't noticed any problems with our frequency of writes. And we don't have a clear/necessary use case.

**Comment by fimad** [comment]
Loads:
Check out the history service. It loads the log file on load.

Unloads:
I think the persistent combinator does this. It takes a component with a StateT stack and automatically saves the state to disk whenever it changes and reads it back on load.

It uses Show and Read to serialize the data. So it's not the most optimal.

**Comment by numberten** [comment]
Loads:
Will take a look at this. Was having trouble doing something similar with simple components, was probably making a silly mistake though.

Unloads:
Yeah I was thinking something more along the lines of writing on a timer to save writes when working with state that updates frequently. But like I mentioned above, I haven't noticed any problems with the frequency of writes using the persistent combinator, so it's not really a problem for now.
